# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('play_count', models.IntegerField(blank=True, null=True)),
                ('listener_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('gender', models.CharField(blank=True, max_length=7)),
                ('disambiguation', models.CharField(blank=True, max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=64)),
                ('play_count', models.IntegerField(blank=True, null=True)),
                ('listener_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('stream_count', models.IntegerField(blank=True, null=True)),
                ('listener_count', models.IntegerField(blank=True, null=True)),
                ('play_count', models.IntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='muzik.Album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='muzik.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='songs',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='muzik.Tag'),
        ),
    ]
