# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzik', '0002_auto_20170928_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(to='muzik.Tag'),
        ),
    ]
