# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzik', '0003_auto_20170928_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='muzik.Release'),
        ),
    ]
