# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzik', '0004_auto_20170929_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release',
        ),
        migrations.AddField(
            model_name='album',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='Release',
        ),
    ]
